server:
  port: 8080

spring.jpa.hibernate.ddl-auto: create
spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/search_engine?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
spring.datasource.username: root
spring.datasource.password: 7413698Aa

webinterface: /admin

config:
  site:
    - url: https://dombulgakova.ru
      name: Дом Булгакова

    - url: https://nikoartgallery.com
      name: Галерея Исскуств Нико

    - url: https://www.lutherancathedral.ru
      name: Собор святых Петра и Павла